// Dummy data for clubs (placeholder images used)
// NOTE: You can expand or replace this with real data later.

export const clubs = [
  {
    id: "1",
    slug: "coding-cats",
    name: "Coding Cats",
    logoUrl: "/coding-cats-logo.jpg",
    shortDescription: "Weekly coding challenges and hack nights.",
    fullDescription:
      "Coding Cats is a student-led organization focused on collaborative learning through weekly coding challenges, hack nights, and project-based workshops.",
    category: "Tech",
    membershipType: "Open",
    email: "codingcats@example.edu",
    social: {
      website: "https://example.edu/coding-cats",
      twitter: "https://twitter.com",
      instagram: "https://instagram.com",
    },
    meetingTimes: "Wednesdays, 6–8 PM @ CS Lab 201",
    events: [
      { title: "Hack Night", date: "2025-10-20", location: "CS Lab 201" },
      { title: "Intro to TypeScript", date: "2025-10-27", location: "CS Auditorium" },
    ],
    images: ["/coding-cats-workshop.jpg", "/members-collaborating.jpg"],
  },
  {
    id: "2",
    slug: "art-circle",
    name: "Art Circle",
    logoUrl: "/art-circle-logo.jpg",
    shortDescription: "Sketch sessions and gallery visits.",
    fullDescription:
      "Art Circle connects artists across campus, organizing sketch sessions, critiques, and local gallery visits to inspire creativity.",
    category: "Arts",
    membershipType: "Open",
    email: "artcircle@example.edu",
    social: { instagram: "https://instagram.com" },
    meetingTimes: "Fridays, 5–6:30 PM @ Studio B",
    events: [
      { title: "Figure Drawing", date: "2025-10-18", location: "Studio B" },
      { title: "Gallery Crawl", date: "2025-10-25", location: "Downtown Arts District" },
    ],
    images: ["/vibrant-art-workshop.png"],
  },
  {
    id: "3",
    slug: "outdoor-adventure",
    name: "Outdoor Adventure",
    logoUrl: "/outdoor-adventure-logo.jpg",
    shortDescription: "Hiking, camping, and nature conservation.",
    fullDescription:
      "Join us for hiking trips, camping weekends, and conservation initiatives. All experience levels welcome.",
    category: "Community",
    membershipType: "Open",
    email: "outdoors@example.edu",
    meetingTimes: "Tuesdays, 7–8 PM @ Rec Center 101",
    events: [
      { title: "Trail Cleanup", date: "2025-10-21", location: "Riverbend Park" },
      { title: "Weekend Campout", date: "2025-11-01", location: "Pine Ridge" },
    ],
    images: ["/diverse-hiking-group.png"],
  },
  {
    id: "4",
    slug: "robotics-guild",
    name: "Robotics Guild",
    logoUrl: "/robotics-guild-logo.jpg",
    shortDescription: "Build robots. Compete. Learn together.",
    fullDescription:
      "Robotics Guild designs, builds, and competes with autonomous robots. We host workshops on electronics, mechanics, and control systems.",
    category: "Tech",
    membershipType: "Closed",
    email: "robotics@example.edu",
    social: { website: "https://example.edu/robotics" },
    meetingTimes: "Mon & Thu, 6–9 PM @ Maker Space",
    events: [
      { title: "Intro to Soldering", date: "2025-10-19", location: "Maker Space" },
      { title: "Regional Competition", date: "2025-11-15", location: "Tech Arena" },
    ],
    images: ["/robotics-lab.jpg"],
  },
  {
    id: "5",
    slug: "book-nook",
    name: "Book Nook",
    logoUrl: "/book-nook-logo.jpg",
    shortDescription: "Monthly reads and lively discussions.",
    fullDescription:
      "Book Nook is a community of readers exploring diverse genres. Join our monthly book club and author talks.",
    category: "Academic",
    membershipType: "Open",
    email: "booknook@example.edu",
    meetingTimes: "First Thursday, 7–8 PM @ Library 3F",
    events: [
      { title: "Author Q&A", date: "2025-10-22", location: "Library Auditorium" },
      { title: "Sci-Fi Night", date: "2025-11-05", location: "Library 3F" },
    ],
    images: ["/book-club.png"],
  },
  {
    id: "6",
    slug: "film-society",
    name: "Film Society",
    logoUrl: "/film-society-logo.jpg",
    shortDescription: "Screenings and film critiques.",
    fullDescription:
      "Film Society hosts weekly screenings and post-film discussions across world cinema and indie films.",
    category: "Arts",
    membershipType: "Open",
    email: "films@example.edu",
    meetingTimes: "Saturdays, 7–10 PM @ Theater 2",
    events: [
      { title: "Classic Noir Night", date: "2025-10-26", location: "Theater 2" },
      { title: "Indie Festival", date: "2025-11-09", location: "Campus Theater" },
    ],
    images: ["/film-screening.jpg"],
  },
  {
    id: "7",
    slug: "basketball-club",
    name: "Basketball Club",
    logoUrl: "/basketball-club-logo.jpg",
    shortDescription: "Pick-up games and tournaments.",
    fullDescription: "Join weekly pick-up games and prepare for intercollegiate tournaments. All skill levels welcome.",
    category: "Sports",
    membershipType: "Open",
    email: "hoops@example.edu",
    meetingTimes: "Tues & Thu, 5–7 PM @ Gym A",
    events: [
      { title: "3v3 Tournament", date: "2025-10-23", location: "Gym A" },
      { title: "Skills Clinic", date: "2025-11-02", location: "Gym A" },
    ],
    images: ["/pickup-game.jpg"],
  },
  {
    id: "8",
    slug: "volunteer-network",
    name: "Volunteer Network",
    logoUrl: "/volunteer-network-logo.jpg",
    shortDescription: "Community service and outreach.",
    fullDescription:
      "We coordinate campus-wide volunteer opportunities and partner with local nonprofits for ongoing projects.",
    category: "Community",
    membershipType: "Open",
    email: "volunteer@example.edu",
    meetingTimes: "Wednesdays, 4–5 PM @ Union 110",
    events: [
      { title: "Food Drive", date: "2025-10-24", location: "Student Union" },
      { title: "Park Restoration", date: "2025-11-07", location: "City Park" },
    ],
    images: ["/community-service.png"],
  },
  {
    id: "9",
    slug: "math-society",
    name: "Math Society",
    logoUrl: "/math-society-logo.jpg",
    shortDescription: "Problem solving and seminars.",
    fullDescription:
      "Math Society explores problem-solving sessions, invited talks, and peer mentoring in mathematics.",
    category: "Academic",
    membershipType: "Closed",
    email: "mathsoc@example.edu",
    meetingTimes: "Mondays, 4–6 PM @ Math 210",
    events: [
      { title: "Putnam Prep", date: "2025-10-29", location: "Math 210" },
      { title: "Number Theory Talk", date: "2025-11-10", location: "Math Hall" },
    ],
  },
  {
    id: "10",
    slug: "dance-collective",
    name: "Dance Collective",
    logoUrl: "/dance-collective-logo.jpg",
    shortDescription: "Choreography and performance.",
    fullDescription:
      "A space for dancers to learn, choreograph, and perform across styles from hip-hop to contemporary.",
    category: "Arts",
    membershipType: "Open",
    email: "dance@example.edu",
    meetingTimes: "Thursdays, 6–8 PM @ Studio A",
    events: [
      { title: "Showcase Rehearsal", date: "2025-10-28", location: "Studio A" },
      { title: "Fall Showcase", date: "2025-11-20", location: "Main Theater" },
    ],
  },
  {
    id: "11",
    slug: "esports-league",
    name: "Esports League",
    logoUrl: "/esports-league-logo.png",
    shortDescription: "Competitive and casual play.",
    fullDescription: "Esports League organizes competitive teams and casual community nights across popular titles.",
    category: "Tech",
    membershipType: "Open",
    email: "esports@example.edu",
    meetingTimes: "Fridays, 7–9 PM @ Gaming Lab",
    events: [
      { title: "LAN Night", date: "2025-10-31", location: "Gaming Lab" },
      { title: "Intercollegiate Match", date: "2025-11-12", location: "Online" },
    ],
  },
  {
    id: "12",
    slug: "running-club",
    name: "Running Club",
    logoUrl: "/running-club-logo.png",
    shortDescription: "Group runs and race prep.",
    fullDescription: "From beginners to marathoners, we do weekly group runs and help each other prepare for races.",
    category: "Sports",
    membershipType: "Open",
    email: "running@example.edu",
    meetingTimes: "Mon, Wed, Fri, 6 AM @ Track",
    events: [
      { title: "5K Time Trial", date: "2025-10-30", location: "Campus Track" },
      { title: "Trail Run", date: "2025-11-08", location: "Forest Loop" },
    ],
  },
  {
    id: "13",
    slug: "bms-college-engineering",
    name: "BMS College of Engineering",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images-bMJrNgO2TXqguZRd23y5rHqvpDOIQc.jpg",
    shortDescription: "Premier engineering institution in Bangalore.",
    fullDescription:
      "BMS College of Engineering, established in 1946, is a leading engineering college in Bangalore focused on excellence in technical education and innovation.",
    category: "Academic",
    membershipType: "Open",
    email: "admissions@bmsce.ac.in",
    social: {
      website: "https://www.bmsce.ac.in",
      instagram: "https://instagram.com/bmscebangalore",
    },
    meetingTimes: "Various - Check department schedules",
    events: [
      { title: "Engineering Fest", date: "2025-11-15", location: "BMS Campus" },
      { title: "Recruitment Drive", date: "2025-12-01", location: "Placement Cell" },
    ],
    images: ["https://hebbkx1anhila5yf.public.blob.vercel-storage.com/images-bMJrNgO2TXqguZRd23y5rHqvpDOIQc.jpg"],
  },
]

export const categories = ["All", "Sports", "Tech", "Arts", "Community", "Academic"]

export const membershipTypes = ["All", "Open", "Closed"]
